### PR TITLE
Run Plone 6.0 Python 3.13 as core job.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Core jobs would be (ignoring 5.2):

* 6.0: 3.9 and 3.13
* 6.1: 3.10 and 3.13

Core schedules would be:

* 6.0: 3.10, 3.11, 3.12
* 6.1: 3.11 and 3.12

See https://github.com/plone/jenkins.plone.org/pull/377#issuecomment-2531353597

### CODE REVIEW

**Review by gforcada — APPROVED** [review]
LGTM! Thanks!

**Comment by gforcada** [comment]
I updated mr.roboto accordingly as well:

```python
py_versions = {'5.2': ['2.7', '3.8'], '6.0': ['3.9', '3.13'], '6.1': ['3.10', '3.13']}
```

**Comment by gforcada** [comment]
The jenkins `Core` (default) view and the `Core schedules` have been updated as well.

Let me know if there is still something off.

**Comment by mauritsvanrees** [comment]
Thanks!

**Pull request merged**
