### PR TITLE
fix pr-job for Plone 4.3

### PR DESCRIPTION
**Pull request by pbauer**
see https://github.com/plone/jenkins.plone.org/commit/4ba1250944c068fde52470c4b4b8b31eea34ee06#commitcomment-14207181

### CODE REVIEW

**Comment by jensens** [comment]
looks good afaict

**Comment by jensens** [comment]
ping @gforcada @tisto @bloodbare  - no testing team in plone-organisation to ping :(

**Comment by pbauer** [comment]
@tisto @gforcada can you please activate this fix on jenkins.plone.org?

**Comment by gforcada** [comment]
:tada: done

@jensens good idea about the plone org testing team

**Comment by gforcada** [comment]
@tisto @jensens I created @plone/testing-team I added just a few members, should we add all those listed here: https://plone.org/community/teams/cit ?

**Comment by jensens** [comment]
@gforcada adding the active participants would be sufficient.

**Pull request merged**
