### PR TITLE
Skip shiningpanda

### PR DESCRIPTION
**Pull request by gforcada**
@mauritsvanrees @fredvd on my local tests (generating the job files locally) it looks fine, run:

```shell
git checkout master
jenkins-jobs --conf jobs/config.ini test jobs/jobs.yml -o old_files
git checkout skip-shiningpanda
jenkins-jobs --conf jobs/config.ini test jobs/jobs.yml -o new_files
meld old_files new_files
```
✨ 

Let me know when is a good time to merge and test it. For me, if we can do on August's last week it would be best as I will be back at work, otherwise, with the kids and running around I can spend some time on the computer but are much more irregular/unpredictable 😅

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Last week August should be good then.

I have not checked this PR yet. But note that I am currently running a [poll](https://community.plone.org/t/plone-6-0-drop-support-for-python-3-7-and-3-8/15549) to see which Python versions people think we should support on Plone 6. That could bring some more changes, but also hopefully make some things a bit easier.

**Comment by gforcada** [comment]
@mauritsvanrees thanks for the pointer to the poll, I voiced my thoughts on it 👍🏾 

With this refactoring, we can support any new python version with a matter of duplicating a few lines on the `jobs.yml` file. The only problem we can have with this new approach is that the `venv` module is removed from python core, which I highly doubt 🤞🏾 

So, I would say, we are pretty safe in this front.

Another matter is if we want to move our testing CI infrastructure over to github actions 😅 but that's a complete other topic 😃

**Review by mauritsvanrees — APPROVED** [review]
I have looked at the changes, and it seems okay to me. Since there are no changes in the generated files, it should be safe to merge.

**Comment by gforcada** [comment]
Merged and jobs updated 🚀

**Pull request merged**
