### PR TITLE
Use https instead of unauthenticated git protocol.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Same as https://github.com/plone/mr.roboto/pull/92

cc @gforcada @fredvd

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Works now, thanks.

**Comment by gforcada** [comment]
thanks for the fix and deploying it! 🙇🏾

**Comment by fredvd** [comment]
@gforcada for my understanding, I was not sure if by updating the jobs through update_jobs.sh which calls jenkins-job-builder, the scripts in the scripts directory are also all synced to the jenkins main server?  

Maurits fixed the URL in the pr-get-info(2).py scripts and these were apparently also updated because they work now.

**Comment by gforcada** [comment]
The scripts are not synced, but are pulled by the update_jobs.sh to create the final XML of each jenkins job and then sent verbatim to the server :)

**Pull request merged**
