### PR TITLE
jenkins-job-builder configuration

### PR DESCRIPTION
**Pull request by gforcada**
As discussed some time ago with @tisto, the idea here is to make a 1:1 translation of our current setup but using [jenkins-job-builder](http://ci.openstack.org/jenkins-job-builder).

As currently [jenkins.plone.org](https://jenkins.plone.org) has *lots* of jobs defined, only the core set will be recreated within this pull request. That means basically Plone 4.3 with both python 2.6 and 2.7 and Plone 5.0 with core tests, robot and AT, all in all just 5 jobs.

This is mostly a test ground so that once we get some experience with jjb and we decide how to proceed further with the testing workflow, we already have a clean and solid configuration to expand on.

### CODE REVIEW

**Comment by gforcada** [comment]
So currently we have 4.3 for python 2.6 and 2.7, there are some configuration that is not available on standard jenkins-job-builder but that we are using, we will need to either decided if we still want it or not.

**Comment by gforcada** [comment]
Plone 5.0 (core and robot) are there, missing AT and all the tweaks on things that jjb does not provide by default.

**Comment by gforcada** [comment]
AT is there also, now "only" the missing parts.

**Comment by tisto** [comment]
Awesome! Will have a look later today...

**Comment by gforcada** [comment]
I have quite a few more things done, will push them later...

Still we have a bit of a problem with current JJB as it *only* allows to add more definitions (say xvfb) but not to extend/override already defined ones.

I already send them a [bug report](https://storyboard.openstack.org/#!/story/2000146), let's see...

**Comment by gforcada** [comment]
Everything that I have is pushed, as you can see adding new things is quite easy: an entry on setup.py and a function is enough.

**Comment by gforcada** [comment]
Updated once again.

To try the current configuration one needs to have on virtualenv jenkins-job-builder from [my fork](https://github.com/gforcada/jenkins-job-builder).

As it can be see on the TODO's entries on the config file, the only remaining configuration to be updated to match 1:1 the current setup is the email configuration.

Once we decided what to do with it, this PR can be merged and start to be used.

**Comment by gforcada** [comment]
Some more work on it: I created another project that define as many PLIPs jobs as needed provided the PLIP has a config file on buildout.coredev branch 5.0 .)

This way we can test all PLIPs as they move forward. Maybe we need to set a cron job to run them on a daily basis or so?

And regarding that I created https://github.com/plone/buildout.coredev/issues/64

**Comment by gforcada** [comment]
@tisto merged! we can now tweak it, I think the foundation is stable enough to not have to start rewriting things all over (hopefully). :tada:

**Comment by tisto** [comment]
Awesome!

**Pull request merged**
