### PR TITLE
Fix request 4.3

### PR DESCRIPTION
**Pull request by gotcha**

### CODE REVIEW

**Comment by tisto** [comment]
@gotcha looks good. Thx! Will merge now and deploy later today...

**Comment by gotcha** [comment]
@tisto can you let me know when you deploy ?

**Comment by tisto** [comment]
@gotcha sure. I have to wait until all current jobs are finished...

**Comment by gotcha** [comment]
@tisto good to know, I was still making it work...

**Comment by gforcada** [comment]
@gotcha I just updated the job, give it a try whenever you can ;)

**Comment by gotcha** [comment]
@gforcada @tisto http://jenkins.plone.org/job/pull-request-4.3/37 can be green !!! :smiley:

**Pull request merged**
