### PR TITLE
generate atcontenttypes and atreferencebrowserwidget translations only for old Plone versiions

### PR DESCRIPTION
**Pull request by erral**
See https://github.com/collective/plone.app.locales/issues/315

### CODE REVIEW

**Review by mauritsvanrees — APPROVED** [review]
LGTM.

I guess there is no other way to test this, then to let the @plone/ai-team put it live.

The current script fails on Plone 6 though. In fact it has never run successfully, because `pip install -r requirements.txt` [fails](https://jenkins.plone.org/view/Translations/job/plone-6.0-i18n/655/console) to find the required setuptools. Could you try to fix that? I guess an extra condition in the if/else near the top would work, calling `pip3` when the Plone version is 6.0. Could be done in a different PR as well, because it has nothing to do with your fix.

**Comment by erral** [comment]
Done. I also updated the i18n-find-untranslated script because it has the same problem.

**Review by mauritsvanrees — APPROVED** [review]
Thanks, I will merge now.
And then an admin can put it live.

**Comment by gforcada** [comment]
I deployed it, but it still fails on plone 6.0 jobs... `pip3` is not the solution, one has to change the job to actually use a python3 virtual environment

**Comment by gforcada** [comment]
btw. I guess that the 4.3, 5.0 and 5.1 can be removed, right? 🤔

**Comment by fredvd** [comment]
@gforcada Something else, but related. I did some jenkin s studying when I didn’t have to drive on my return trip from Italy.  The many jobs now on jenkins.plone.org are all free form project and many have a comment ‘created by jenkins -job-builder’, which is a python module .   But me.roboto is not depending on that package.

are the current jobs still autogenerated by mr.roboto or anithee tol/from a repo, or are they nowadays cloned from an existing job when  a new combination is needed?

**Comment by fredvd** [comment]
Ah, found most of questions. The jobs are configured in this repo and jenkins-job-builder is pulled in as a git submodule. 

So is this repo should be checkout out on our local dev machines and when you want to update jenkins you run it locally on your machine with your own credentials @gforcada ?

**Comment by gforcada** [comment]
you got it! :) indeed, there is a `jobs` folder in this repo where all the configurations are stored, scripts and what not. And to make it easy there is a shell script on the top level to run it as well. Improvements are more than welcome on any part

**Pull request merged**
